packages:
  - cli
  - ui
  - core
  - packs
  - packages/*

ignoredBuiltDependencies:
  - '@devm33/node-pty'
  - '@swc/core'
  - keytar-forked-forked
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - nx
